examples/p-chain/export.ts: P-chain export do not depends on the target address
Unfortunately, as currently written, the two following expression:

  bech32ToBytes(X_CHAIN_ADDRESS)

and

  bech32ToBytes(P_CHAIN_ADDRESS)

intra-account results in the same output. The generated UTxO will
include a pseudo-CorETH address which will prevent import on the C-chain
and return the following error:

  Error: import tx transfer failed verification: wrong signature: expected signature from JTWYVMiL9CmJvWBVbhZzMtyV8wW4C1Ztt but got from auLWN59QX8b9hFwt1e5oLaCRWMM1j4HU